services:
  pocketbase:
    build:
      context: .
      dockerfile: ./pocketbase.Dockerfile
      args:
        - PB_VERSION=0.39.3
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - ./pb_data:/app/pb_data
      - ./pb_migrations:/app/pb_migrations
    env_file:
      - .env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8090:8090"

  nginx-without-ssl:
    container_name: nginx-without-ssl
    build:
      context: ./nginx
      dockerfile: nginx-without-ssl.Dockerfile
    volumes:
      - ./nginx/nginx-without-ssl.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
      - ./nginx/chain.pem:/etc/chain.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pocketbase

  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    # и снова мониторуем директорию nginx
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: certbot.Dockerfile
      # задаем переменные среды
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
    depends_on:
      - nginx-without-ssl
