worker_processes auto;

events {
}

http {
  server {
    listen     80;

    # делаем переадресацию с HTTP на HTTPS
    location / {
      return 301 https://$host$request_uri;
    }

    # URL certbot'a, где он будет слушать входящие
    # подключения во время выдачи SSL
    location /.well-known {
      proxy_pass http://172.17.0.1:6000;
    }
  }
}
